VALORES_DEPENDENCIA_ASIGNADA = [
    "COBRO",
    "CONTROL_A_LAS_OPERACIONES_ILEGALES",
    "GERENCIA_ADMINISTRATIVA",
    "GERENCIA_ADMINISTRATIVA_NOT",
    "GERENCIA_ADMINISTRATIVA_PQRSD",
    "GERENCIA_ADMINISTRATIVA_SERV_C",
    "GERENCIA_DE_FISCALIZACION",
    "GERENCIA_FINANCIERA",
    "OFICINA_ASESORA_DE_PLANEACION",
    "OFICINA_DE_CONTROL_INTERNO",
    "OFICINA_DE_TECNOLOGIA_DE_LA_INFORMACION",
    "OFICINA_JURIDICA",
    "PRESIDENCIA",
    "RELACIONAMIENTO_COMERCIAL",
    "SECRETARIA_TECNICA_DEL_CONSEJO_NACIONAL_DE_JSA",
    "SEGUIMIENTO_CONTRACTUAL",
    "VICEPRESIDENCIA_DESARROLLO_ORGANIZACIONAL",
    "VICEPRESIDENCIA_DE_OPERACIONES",
    "VICEPRESIDENCIA_DESARROLLO_COMERCIAL"

]


VALORES_REEMPLAZO_DEPENDENCIA_ASIGNADA = {
}