VALORES_LINEA_NEGOCIO = [
    "CHANCES",
    "COBRO_COACTIVO",
    "JUEGOS_OPERADOS_POR_INTERNET",
    "LOCALIZADOS",
    "LOTERIAS",
    "NO_COMERCIAL",
    "NOVEDOSOS",
    "PQRSD",
    "PROMOCIONALES_POR_CONCEPTO",
    "PROMOCIONALES_POR_RESOLUCION",
    "RIFAS"
]


VALORES_REEMPLAZO_LINEA_NEGOCIO = {
}