VALORES_DEPENDENCIA = [
    "CONTROL INTERNO",
    "DIRECCION DE GESTION DE TECNOLOGIAS DE INFORMACION",
    "DIRECCION DE PARAFISCALES",
    "DIRECCION DE PENSIONES",
    "DIRECCION DE SEGUIMIENTO Y MEJORAMIENTO DE PROCESOS",
    "DIRECCION DE SERVICIOS INTEGRADOS DE ATENCION AL CIUDADANO",
    "GESTION DE RELACIONES CON EL CIUDADANO CLIENTES PARAFISCALES Y GRUPOS DE INTERES",
    "GESTION DE SOLICITUDES DE OBLIGACIONES PENSIONALES",
    "GRUPO DE CONTROL INTERNO DISCIPLINARIO",
    "SEGURIDAD DE LA INFORMACION",
    "SUBDIRECCION FINANCIERA",
    "SUBDIRECCION ADMINISTRATIVA",
    "SUBDIRECCION DE COBRANZAS",
    "SUBDIRECCION DE DEFENSA JUDICIAL PENSIONAL",
    "SUBDIRECCION DE DETERMINACION DE DERECHOS PENSIONALES",
    "SUBDIRECCION DE DETERMINACION DE OBLIGACIONES",
    "SUBDIRECCION DE DETERMINACION DE OBLIGACIONES PARAFISCALES",
    "SUBDIRECCION DE GESTION DOCUMENTAL",
    "SUBDIRECCION DE GESTION HUMANA",
    "SUBDIRECCION DE INTEGRACION DE APORTES PARAFISCALES",
    "SUBDIRECCION DE NOMINA",
    "SUBDIRECCION DE NOMINA DE PENSIONADOS",
    "SUBDIRECCION DE NORMALIZACION DE EXPEDIENTES PENSIONALES",
    "SUBDIRECCION FINANCIERA",
    "SUBDIRECCION JURIDICA DE PARAFISCALES",
    "SUBDIRECCION JURIDICA PENSIONAL"
]


VALORES_REEMPLAZO_DEPENDENCIA = {
    "SUBDIRECCION  FINANCIERA" : "SUBDIRECCION FINANCIERA",
}