VALORES_DIRECCION_SECCIONAL = [
    "DIRECCION DE GESTION DE TECNOLOGIAS DE INFORMACION",
    "DIRECCION DE PARAFISCALES",
    "DIRECCION DE PENSIONES",
    "DIRECCION DE SOPORTE Y DESARROLLO ORGANIZACIONAL",
    "DIRECCION GENERAL",
    "DIRECCION JURIDICA",
    "DIRECCION DE SERVICIOS INTEGRADOS DE ATENCION AL CIUDADANO",
    "SUBDIRECCION DE DETERMINACION DE DERECHOS PENSIONALES",
    "DIRECCION DE PARAFISCALES",
    "DIRECCION DE SEGUIMIENTO Y MEJORAMIENTO DE PROCESOS"
]


VALORES_REEMPLAZO_DIRECCION_SECCIONAL = {
}