VALORES_CLASIFICACION = [
    "CONSULTA",
    "DENUNCIA",
    "DERECHO DE PETICIÓN",
    "ENTIDAD EXTERNA",
    "FELICITACIÓN",
    "LAVADO DE ACTIVOS",
    "NO APLICA",
    "PETICIÓN DE INFORMACIÓN",
    "QUEJA DISCIPLINARIA",
    "QUEJA POR ATENCIÓN",
    "RECLAMO",
    "SIN CLASIFICAR",
    "SUGERENCIA"
]


VALORES_REEMPLAZO_CLASIFICACION ={
}