VALORES_ESTADO_SOLICITUD = [
    "DESISTIDA",
    "ESTUDIO DE COMPETENCIAS",
    "ESTUDIO DE SOLUCION",
    "PENDIENTE DE INFORMACION",
    "TERMINADA",
    "VENCIDA"
]



VALORES_REEMPLAZO_ESTADO_SOLICITUD ={
}