VALORES_DEPENDENCIA_DIAN = {
    'nivel central',
    'direccion seccional de impuestos y aduanas de armenia',
    'direccion seccional de impuestos de barranquilla',
    'direccion seccional de aduanas de bogota',
    'direccion seccional de impuestos y aduanas de bucaramanga',
    'direccion seccional de impuestos de cali',
    'direccion seccional de impuestos de cartagena',
    'direccion seccional de impuestos de cucuta',
    'direccion seccional de impuestos y aduanas de girardot',
    'direccion seccional de impuestos y aduanas de ibague',
    'direccion seccional de impuestos y aduanas de manizales',
    'direccion seccional de impuestos de medellin',
    'direccion seccional de impuestos y aduanas de monteria',
    'direccion seccional de impuestos y aduanas de neiva',
    'direccion seccional de impuestos y aduanas de pasto',
    'direccion seccional de impuestos y aduanas de palmira',
    'direccion seccional de impuestos y aduanas de pereira',
    'direccion seccional de impuestos y aduanas de popayan',
    'direccion seccional de impuestos y aduanas de quibdo',
    'direccion seccional de impuestos y aduanas de santa marta',
    'direccion seccional de impuestos y aduanas de tunja',
    'direccion seccional de impuestos y aduanas de tulua',
    'direccion seccional de impuestos y aduanas de villavicencio',
    'direccion seccional de impuestos y aduanas de sincelejo',
    'direccion seccional de impuestos y aduanas de valledupar',
    'direccion seccional de impuestos y aduanas de riohacha',
    'direccion seccional de impuestos y aduanas de sogamoso',
    'direccion seccional de impuestos y aduanas de san andres',
    'direccion seccional de impuestos y aduanas de florencia',
    'direccion seccional de impuestos y aduanas de barrancabermeja',
    'direccion seccional de impuestos de grandes contribuyentes',
    'direccion seccional de impuestos de bogota',
    'direccion seccional de impuestos y aduanas de arauca',
    'direccion seccional de impuestos y aduanas de buenaventura',
    'direccion seccional delegada de impuestos y aduanas de cartago',
    'direccion seccional de impuestos y aduanas de ipiales',
    'direccion seccional de impuestos y aduanas de leticia',
    'direccion seccional de impuestos y aduanas de maicao',
    'direccion seccional delegada de impuestos y aduanas de tumaco',
    'direccion seccional de impuestos y aduanas de uraba',
    'direccion seccional delegada de impuestos y aduanas de puerto carreno',
    'direccion seccional delegada de impuestos y aduanas de inirida',
    'direccion seccional de impuestos y aduanas de yopal',
    'direccion seccional delegada de impuestos y aduanas mitu',
    'direccion seccional delegada de impuestos y aduanas de puerto asis',
    'direccion seccional de aduanas de cartagena',
    'direccion seccional delegada de impuestos y aduanas de san jose de guaviare',
    'direccion seccional delegada de impuestos y aduanas de pamplona',
    'direccion seccional de aduanas de barranquilla',
    'direccion seccional de aduanas de cali',
    'direccion seccional de aduanas de cucuta',
    'direccion seccional de aduanas de medellin',
    # se agregaron de mas
    # 'subdireccion de gestion de asistencia al cliente',
    # 'impuestos y aduanas de inirida mitu puerto carreno y san jose del guaviare',
    # 'subdireccion de gestion tecnica aduanera',
    # 'subdireccion de gestion de analisis operacional',
    # 'subdireccion de gestion de fiscalizacion tributaria',
    # 'subdireccion de gestion de normativa y doctrina',
    # 'subdireccion de gestion de recaudo y cobranzas',
    # 'defensor del contribuyente y del usuario aduanero'


}


VALORES_REEMPLAZO_DEPENDENCIA_DIAN = {
    'direccion seccional de impuestos barranquilla': 'direccion seccional de impuestos de barranquilla',
    'direccion seccional de impuestos cali': 'direccion seccional de impuestos de cali',
    'direccion seccional de impuestos cartagena': 'direccion seccional de impuestos de cartagena',
    'direccion seccional de impuestos cucuta': 'direccion seccional de impuestos de cucuta',
    'direccion seccional de impuestos medellin': 'direccion seccional de impuestos de medellin',
    'direccion seccional de impuestos grandes contribuyentes': 'direccion seccional de impuestos de grandes contribuyentes',
    'direccion seccional de impuestos bogota': 'direccion seccional de impuestos de bogota',
    'direccion seccional de impuestos y aduanas armenia': 'direccion seccional de impuestos y aduanas de armenia',
    'direccion seccional de impuestos y aduanas bucaramanga': 'direccion seccional de impuestos y aduanas de bucaramanga',
    'direccion seccional de impuestos y aduanas girardot': 'direccion seccional de impuestos y aduanas de girardot',
    'direccion seccional de impuestos y aduanas ibague': 'direccion seccional de impuestos y aduanas de ibague',
    'direccion seccional de impuestos y aduanas manizales': 'direccion seccional de impuestos y aduanas de manizales',
    'direccion seccional de impuestos y aduanas monteria': 'direccion seccional de impuestos y aduanas de monteria',
    'direccion seccional de impuestos y aduanas neiva': 'direccion seccional de impuestos y aduanas de neiva',
    'direccion seccional de impuestos y aduanas pasto': 'direccion seccional de impuestos y aduanas de pasto',
    'direccion seccional de impuestos y aduanas palmira': 'direccion seccional de impuestos y aduanas de palmira',
    'direccion seccional de impuestos y aduanas pereira': 'direccion seccional de impuestos y aduanas de pereira',
    'direccion seccional de impuestos y aduanas popayan': 'direccion seccional de impuestos y aduanas de popayan',
    'direccion seccional de impuestos y aduanas quibdo': 'direccion seccional de impuestos y aduanas de quibdo',
    'direccion seccional de impuestos y aduanas santa marta': 'direccion seccional de impuestos y aduanas de santa marta',
    'direccion seccional de impuestos y aduanas tunja': 'direccion seccional de impuestos y aduanas de tunja',
    'direccion seccional de impuestos y aduanas tulua': 'direccion seccional de impuestos y aduanas de tulua',
    'direccion seccional de impuestos y aduanas villavicencio': 'direccion seccional de impuestos y aduanas de villavicencio',
    'direccion seccional de impuestos y aduanas sincelejo': 'direccion seccional de impuestos y aduanas de sincelejo',
    'direccion seccional de impuestos y aduanas valledupar': 'direccion seccional de impuestos y aduanas de valledupar',
    'direccion seccional de impuestos y aduanas riohacha': 'direccion seccional de impuestos y aduanas de riohacha',
    'direccion seccional de impuestos y aduanas sogamoso': 'direccion seccional de impuestos y aduanas de sogamoso',
    'direccion seccional de impuestos y aduanas san andres': 'direccion seccional de impuestos y aduanas de san andres',
    'direccion seccional de impuestos y aduanas florencia': 'direccion seccional de impuestos y aduanas de florencia',
    'direccion seccional de impuestos y aduanas barrancabermeja': 'direccion seccional de impuestos y aduanas de barrancabermeja',
    'direccion seccional de impuestos y aduanas arauca': 'direccion seccional de impuestos y aduanas de arauca',
    'direccion seccional de impuestos y aduanas buenaventura': 'direccion seccional de impuestos y aduanas de buenaventura',
    'direccion seccional delegada de impuestos y aduanas cartago': 'direccion seccional delegada de impuestos y aduanas de cartago',
    'direccion seccional de impuestos y aduanas ipiales': 'direccion seccional de impuestos y aduanas de ipiales',
    'direccion seccional de impuestos y aduanas leticia': 'direccion seccional de impuestos y aduanas de leticia',
    'direccion seccional de impuestos y aduanas maicao': 'direccion seccional de impuestos y aduanas de maicao',
    'direccion seccional delegada de impuestos y aduanas tumaco': 'direccion seccional delegada de impuestos y aduanas de tumaco',
    'direccion seccional de impuestos y aduanas uraba': 'direccion seccional de impuestos y aduanas de uraba',
    'direccion seccional delegada de impuestos y aduanas puerto carreno': 'direccion seccional delegada de impuestos y aduanas de puerto carreno',
    'direccion seccional delegada de impuestos y aduanas inirida': 'direccion seccional delegada de impuestos y aduanas de inirida',
    'direccion seccional de impuestos y aduanas yopal': 'direccion seccional de impuestos y aduanas de yopal',
    'direccion seccional delegada de impuestos y aduanas puerto asis': 'direccion seccional delegada de impuestos y aduanas de puerto asis',
    'direccion seccional delegada de impuestos y aduanas san jose de guaviare': 'direccion seccional delegada de impuestos y aduanas de san jose de guaviare',
    'direccion seccional delegada de impuestos y aduanas pamplona': 'direccion seccional delegada de impuestos y aduanas de pamplona',
    'direccion seccional de aduanas bogota':'direccion seccional de aduanas de bogota',
    'direccion seccional de aduanas cartagena':'direccion seccional de aduanas de cartagena',
    'direccion seccional de aduanas barranquilla':'direccion seccional de aduanas de barranquilla',
    'direccion seccional de aduanas cali':'direccion seccional de aduanas de cali',
    'direccion seccional de aduanas cucuta':'direccion seccional de aduanas de cucuta',
    'direccion seccional de aduanas medellin':'direccion seccional de aduanas de medellin',

}