VALORES_CATEGORIA_1 = [
    "ACTAS DE REUNION",
    "DENUNCIA",
    "DENUNCIAS PARA DETERMINACION",
    "FELICITACIONES",
    "INFORMES ENTIDADES DE CONTROL Y VIGILANCIA",
    "NOTIFICACIONES PENSIONES",
    "QUEJAS",
    "RESOLUCIONES"
]

VALORES_REEMPLAZO_CATEGORIA_1 = {
}