VALORES_CLASIFICACION = [
    "ACCIONES CONSTITUCIONALES",
    "ACTAS",
    "ACTOS ADMINISTRATIVOS",
    "CERTIFICACIONES PENSIONALES",
    "CONCEPTOS",
    "DENUNCIAS DE INTEGRACION DE APORTES PARAFISCALES",
    "DENUNCIAS PENALES",
    "DERECHOS DE PETICION DE CONSULTA",
    "DERECHOS DE PETICION DE FONDO",
    "DERECHOS DE PETICION DE INFORMACION Y TRAMITE",
    "EXPEDIENTES DE COBRO",
    "EXPEDIENTES DE DETERMINACION",
    "EXPEDIENTES PENSIONALES",
    "GESTION DE INFORMACION",
    "INFORMES",
    "NOTIFICACIONES",
    "NOVEDAD DE NOMINA",
    "OFICIOS DE TRASLADO POR NO COMPETENCIA",
    "OFICIOS POR FALTA DE CLARIDAD DE INFORMACION",
    "PROCESOS ADMINISTRATIVOS",
    "PROCESOS LABORALES",
    "QUEJAS RECLAMOS SUGERENCIAS FELICITACIONES DENUNCIAS",
    "REGISTROS DE ADMINISTRACION DE COMUNICACIONES OFICIALES ENTRADA Y SALIDA",
    "SANCIONES"
]

VALORES_REEMPLAZO_CLASIFICACION = {
}